"""Map topics/industries to proprietary dataset vertical keys."""
from __future__ import annotations
VERTICALS = frozenset({"crm_automation","saas","d2c_skincare","dental_clinics","automotive_retail","agency_services","restaurants","healthcare_saas","logistics","fintech","edtech","festive_retail","event_services","wedding_services","decor_retail","gifting_retail","local_services","home_services","creator_business"})
_ALIASES = {"crm_automation":"crm_automation","b2b_saas":"saas","revops_sales_automation":"crm_automation","ai_workflow_automation":"saas","fashion":"d2c_skincare","consumer":"d2c_skincare","ecommerce_retail":"d2c_skincare","festive_retail":"festive_retail","event_services":"event_services","wedding_services":"wedding_services","decor_retail":"decor_retail","gifting_retail":"gifting_retail","local_services":"local_services","home_services":"home_services","creator_business":"creator_business","healthcare":"healthcare_saas","clinic_workflow":"dental_clinics","dental_saas":"dental_clinics","automotive":"automotive_retail","automotive_retail":"automotive_retail","finance":"fintech","education":"edtech","food":"restaurants","logistics":"logistics"}
def resolve_vertical(topic: str, industry: str, domain: str | None = None) -> str:
    if domain and domain in VERTICALS: return domain
    if domain and domain in _ALIASES: return _ALIASES[domain]
    hay = f"{topic} {industry}".lower()
    rules = [(("crm","pipedrive","hubspot","salesforce","zoho crm"),"crm_automation"),(("skincare","cosmetic","beauty","serum","moisturizer","nykaa"),"d2c_skincare"),(("ganesh","diwali","navratri","puja","rangoli","festive decor"),"festive_retail"),(("mandap","wedding decor","sangeet","bridal","shaadi"),"wedding_services"),(("event setup","drone show","light show","event rental"),"event_services"),(("decoration kit","home decor","apartment decor","decor products"),"decor_retail"),(("gift hamper","corporate gifting","return gift"),"gifting_retail"),(("dental","dentist","orthodont"),"dental_clinics"),(("car dealer","garage","automotive retail","auto repair"),"automotive_retail"),(("restaurant","qsr","cloud kitchen","cafe"),"restaurants"),(("marketing agency","creative agency","digital agency"),"agency_services"),(("clinic","hospital","patient","healthcare saas"),"healthcare_saas"),(("logistics","freight","warehouse","3pl"),"logistics"),(("fintech","payments","lending","neobank"),"fintech"),(("edtech","online course","lms","tutoring"),"edtech"),(("urban company","justdial","local service","hyperlocal"),"local_services"),(("plumber","electrician","home cleaning","pest control"),"home_services"),(("creator","influencer","youtube channel"),"creator_business"),(("saas","software","subscription","b2b"),"saas")]
    for terms, vertical in rules:
        if any(t in hay for t in terms): return vertical
    return "saas"