"""Finance: invoices and payment links."""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests

from iidatech.integrations.registry import _env

_TIMEOUT = float(os.getenv("IIDATECH_INTEGRATION_TIMEOUT", "30"))


def generate_invoice_pdf(*, out_path: Path, client: str, amount: float, currency: str = "USD", invoice_id: str = "") -> dict[str, Any]:
    inv_id = invoice_id or f"INV-{uuid.uuid4().hex[:8].upper()}"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas

        c = canvas.Canvas(str(out_path), pagesize=letter)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(72, 720, "INVOICE")
        c.setFont("Helvetica", 11)
        c.drawString(72, 690, f"Invoice ID: {inv_id}")
        c.drawString(72, 670, f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
        c.drawString(72, 650, f"Bill To: {client}")
        c.drawString(72, 620, f"Amount: {currency} {amount:,.2f}")
        c.drawString(72, 590, "Generated by IIDATECH Employee OS")
        c.save()
        return {"ok": True, "invoice_id": inv_id, "invoice_path": str(out_path), "format": "pdf"}
    except Exception as exc:
        json_path = out_path.with_suffix(".json")
        json_path.write_text(
            json.dumps({"invoice_id": inv_id, "client": client, "amount": amount, "currency": currency}, indent=2),
            encoding="utf-8",
        )
        return {"ok": True, "invoice_id": inv_id, "invoice_path": str(json_path), "format": "json", "warning": str(exc)[:120]}


def create_payment_link(*, amount_cents: int, currency: str, description: str, success_url: str, cancel_url: str) -> dict[str, Any]:
    if _env("STRIPE_SECRET_KEY"):
        try:
            from backend_integrations import create_stripe_checkout_session
            return create_stripe_checkout_session({
                "amount_cents": amount_cents,
                "currency": currency,
                "product_name": description,
                "success_url": success_url,
                "cancel_url": cancel_url,
            })
        except ImportError:
            pass
    key_id = _env("RAZORPAY_KEY_ID")
    key_secret = _env("RAZORPAY_KEY_SECRET")
    if key_id and key_secret:
        try:
            response = requests.post(
                "https://api.razorpay.com/v1/payment_links",
                auth=(key_id, key_secret),
                json={
                    "amount": amount_cents,
                    "currency": currency.upper(),
                    "description": description[:240],
                    "callback_url": success_url,
                },
                timeout=_TIMEOUT,
            )
            if 200 <= response.status_code < 300:
                data = response.json() if response.content else {}
                return {"ok": True, "provider": "razorpay", "payment_link": data.get("short_url") or data.get("id")}
            return {"ok": False, "provider": "razorpay", "message": response.text[:240]}
        except Exception as exc:
            return {"ok": False, "provider": "razorpay", "message": str(exc)[:200]}
    return {"ok": False, "provider": "payments", "message": "Configure STRIPE_SECRET_KEY or RAZORPAY keys"}