// @ts-nocheck
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mcrxmryuitqehjizsaea"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcnhtcnl1aXRxZWhqaXpzYWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MjY3OTMsImV4cCI6MjA4ODEwMjc5M30.f9XZPfUT8UQT-dPxjECMSPZ_PnbH0Y0rxsPnSgagBUI"