"""IIDATECH SQL storage package."""
from iidatech.storage.cache_repository import (
    get_cached_search,
    hash_query,
    increment_cache_hit,
    infer_cache_kind,
    insert_cached_search,
    log_api_cost,
    ttl_hours_for_kind,
    update_provider_stats,
)
from iidatech.storage.cost_dashboard import build_cost_summary
from iidatech.storage.db import (
    ensure_cache_schema,
    ensure_execution_schema,
    ensure_semantic_schema,
    get_backend,
    get_connection,
    get_database_url,
    init_schema,
    row_to_dict,
    sql_placeholder,
    sql_storage_ready,
    topic_tokens,
)
from iidatech.storage.provider_cache import cached_provider_call
from iidatech.storage.repositories import (
    bank_row_counts,
    get_benchmarks,
    get_buyer_voice,
    get_competitor_pricing,
    get_supplier_costs,
    insert_evidence_record,
    insert_report,
    search_similar_records,
)
from iidatech.storage.semantic_memory import (
    backfill_embeddings,
    search_cross_industry_patterns,
    search_semantic_records,
    search_similar_reports,
    semantic_memory_ready,
)

__all__ = [
    "build_cost_summary",
    "cached_provider_call",
    "ensure_cache_schema",
    "ensure_execution_schema",
    "ensure_semantic_schema",
    "get_backend",
    "get_cached_search",
    "get_connection",
    "get_database_url",
    "hash_query",
    "increment_cache_hit",
    "infer_cache_kind",
    "init_schema",
    "insert_cached_search",
    "log_api_cost",
    "row_to_dict",
    "sql_placeholder",
    "sql_storage_ready",
    "topic_tokens",
    "ttl_hours_for_kind",
    "update_provider_stats",
    "bank_row_counts",
    "get_benchmarks",
    "get_buyer_voice",
    "get_competitor_pricing",
    "get_supplier_costs",
    "insert_evidence_record",
    "insert_report",
    "search_similar_records",
    "backfill_embeddings",
    "search_semantic_records",
    "search_similar_reports",
    "search_cross_industry_patterns",
    "semantic_memory_ready",
]